runtimes:
  - name: vllm
    image: ghcr.io/tokenforge/worker-vllm:latest
    gpu: 1
    cpu: "2"
    mem: "16Gi"
    env:
      MAX_MODEL_LEN: "8192"
  - name: transformers
    image: ghcr.io/tokenforge/worker-transformers:latest
    gpu: 1
    cpu: "2"
    mem: "16Gi"
