name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build API
        run: cd api && go build -v ./...

      - name: Test API
        run: cd api && go test -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push vLLM worker image
        uses: docker/build-push-action@v4
        with:
          context: ./workers/worker-vllm
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/worker-vllm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Transformers worker image
        uses: docker/build-push-action@v4
        with:
          context: ./workers/worker-transformers
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/worker-transformers:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Docker Compose
        run: docker-compose up -d postgres minio worker-stub

      - name: Wait for services
        run: sleep 10

      - name: Run API server
        run: cd api && go run . &

      - name: Wait for API server
        run: sleep 5

      - name: Run smoke test
        run: bash scripts/smoke.sh
