name: Docker Hub Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.actor }}/tokenforge

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build API
        run: cd api && go build -v ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push vLLM worker image
        uses: docker/build-push-action@v4
        with:
          context: ./workers/worker-vllm
          file: ./workers/worker-vllm/Dockerfile.simple
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-worker-vllm:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Transformers worker image
        uses: docker/build-push-action@v4
        with:
          context: ./workers/worker-transformers
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-worker-transformers:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
